let arrMainIdeaQues = [
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Wildlife conservation efforts have made great strides in protecting endangered species through legislation, sanctuaries, and breeding programs. However, many experts believe that without addressing the root causes of habitat destruction and climate change, these efforts will be insufficient.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Conservation efforts are successfully protecting endangered species.",
        "AnswerChoiceB": "Without addressing root causes like habitat destruction, conservation efforts may fail.",
        "AnswerChoiceC": "Breeding programs are the most effective means of wildlife conservation.",
        "AnswerChoiceD": "Habitat destruction is the sole cause of species endangerment.",
        "CorrectAnswer": "Without addressing root causes like habitat destruction, conservation efforts may fail.",
        "Explanation": "This option best encapsulates the overall message that conservation efforts are crucial but may fail unless deeper issues are addressed.",
        "Hint": "Focus on the phrase \"without addressing the root causes\" as it reveals the core concern of the passage."
    },

    {
        "TypeofQuestion": "Main Idea",
        "Passage": "While the internet has revolutionized global communication, it has also led to significant concerns about privacy and data security. As more personal information is shared online, the risk of cybercrime increases.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "The internet has improved communication but also raised privacy concerns.",
        "AnswerChoiceB": "Personal information should not be shared online due to security risks.",
        "AnswerChoiceC": "Cybercrime is the biggest problem caused by the internet.",
        "AnswerChoiceD": "People need to protect their data while using the internet.",
        "CorrectAnswer": "The internet has improved communication but also raised privacy concerns.",
        "Explanation": "This answer addresses both sides of the passage—the advantages of communication and the concerns about privacy.",
        "Hint": "The passage contrasts two key ideas: improvement in communication and privacy concerns."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Advancements in electric vehicle technology are making it easier for consumers to switch from gasoline-powered cars. With more affordable models on the market and the growing availability of charging stations, electric vehicles are becoming a more practical choice.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Electric vehicles are now more affordable than gasoline-powered cars.",
        "AnswerChoiceB": "The popularity of electric vehicles is increasing due to technological improvements.",
        "AnswerChoiceC": "Charging stations are more available than ever before.",
        "AnswerChoiceD": "People are finding it easier to switch to electric vehicles.",
        "CorrectAnswer": "The popularity of electric vehicles is increasing due to technological improvements.",
        "Explanation": "This captures both the growing accessibility of electric cars and the reasons why they are becoming more practical.",
        "Hint": "Look at \"making it easier for consumers\" and \"more affordable\" to find the overall trend of the passage."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The study of ancient civilizations offers invaluable insight into human culture and societal development. By examining historical artifacts and records, researchers can better understand how societies evolved over time.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Studying ancient civilizations helps us learn about human culture and development.",
        "AnswerChoiceB": "Artifacts from ancient civilizations offer clues about daily life in the past.",
        "AnswerChoiceC": "Researchers are interested in learning how societies developed.",
        "AnswerChoiceD": "Historical records provide the most insight into societal development.",
        "CorrectAnswer": "Studying ancient civilizations helps us learn about human culture and development.",
        "Explanation": "This option summarizes the broad purpose of studying ancient civilizations, without focusing too narrowly on one detail.",
        "Hint": "The entire passage focuses on the value of studying ancient civilizations to understand society and culture."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Many businesses have shifted to remote work in response to the global pandemic. While this transition has offered benefits such as flexibility and reduced commute times, it has also presented challenges like maintaining productivity and fostering collaboration.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Remote work has both benefits and challenges for businesses.",
        "AnswerChoiceB": "Remote work increases flexibility but decreases collaboration.",
        "AnswerChoiceC": "The global pandemic has forced many businesses to adopt remote work.",
        "AnswerChoiceD": "Businesses are struggling to maintain productivity during the pandemic.",
        "CorrectAnswer": "Remote work has both benefits and challenges for businesses.",
        "Explanation": "This choice captures the main theme that remote work has both positive and negative aspects, according to the passage.",
        "Hint": "Pay attention to \"benefits\" and \"challenges\" to grasp the passage's balanced view."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The invention of the printing press revolutionized access to information by making books more affordable and widely available. This technological advance contributed to the spread of knowledge during the Renaissance and laid the foundation for the modern information age.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "The printing press made books more affordable and helped spread knowledge.",
        "AnswerChoiceB": "The Renaissance could not have happened without the invention of the printing press.",
        "AnswerChoiceC": "The printing press laid the foundation for modern information technology.",
        "AnswerChoiceD": "Books became widely available after the invention of the printing press.",
        "CorrectAnswer": "The printing press made books more affordable and helped spread knowledge.",
        "Explanation": "This summarizes both the impact on books and the broader role of the printing press in spreading knowledge.",
        "Hint": "The phrase \"spread of knowledge\" is key to identifying the correct answer."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Global temperatures have risen significantly in the past century, leading to widespread changes in weather patterns. These changes are contributing to more frequent natural disasters, such as hurricanes, floods, and wildfires, which are causing both economic and environmental damage.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Climate change is causing an increase in natural disasters and their impact.",
        "AnswerChoiceB": "Global temperatures are rising faster than predicted.",
        "AnswerChoiceC": "Hurricanes, floods, and wildfires are becoming more frequent.",
        "AnswerChoiceD": "Environmental damage is increasing due to global warming.",
        "CorrectAnswer": "Climate change is causing an increase in natural disasters and their impact.",
        "Explanation": "This answer addresses both the cause (climate change) and its consequences (natural disasters and damage).",
        "Hint": "Look for the connection between \"widespread changes in weather patterns\" and natural disasters."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Public health campaigns have successfully reduced smoking rates in many countries. However, rising rates of obesity and other lifestyle-related diseases have led health experts to call for new strategies that focus on improving diet and increasing physical activity.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Smoking rates have declined, but obesity rates are rising.",
        "AnswerChoiceB": "Public health campaigns have been successful in reducing smoking.",
        "AnswerChoiceC": "New strategies are needed to address obesity and other lifestyle diseases.",
        "AnswerChoiceD": "Health experts are concerned about rising obesity rates.",
        "CorrectAnswer": "New strategies are needed to address obesity and other lifestyle diseases.",
        "Explanation": "This answer addresses the main point of the passage: the need for new public health strategies to tackle obesity.",
        "Hint": "The phrase \"call for new strategies\" is a key clue to the overall theme."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Space exploration has led to many technological advancements, including innovations in materials, telecommunications, and medical devices. These technologies, which were originally developed for use in space missions, have since been adapted for use on Earth, benefiting society in numerous ways.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Space missions have led to innovations in telecommunications.",
        "AnswerChoiceB": "Technological advancements from space exploration have benefited society on Earth.",
        "AnswerChoiceC": "Medical devices used in space missions have been adapted for use on Earth.",
        "AnswerChoiceD": "Space exploration has led to the development of new materials.",
        "CorrectAnswer": "Technological advancements from space exploration have benefited society on Earth.",
        "Explanation": "This answer encapsulates the broad theme of how space exploration has led to benefits on Earth.",
        "Hint": "The phrase \"benefiting society in numerous ways\" signals the broad impact being discussed."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The development of renewable energy sources, such as solar and wind power, is critical for reducing reliance on fossil fuels and mitigating the effects of climate change. While these technologies have seen significant growth, more investment is needed to make them widely accessible.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Renewable energy sources are growing rapidly but need further investment.",
        "AnswerChoiceB": "Solar and wind power are the best alternatives to fossil fuels.",
        "AnswerChoiceC": "Renewable energy is essential for mitigating climate change.",
        "AnswerChoiceD": "Investment in renewable energy is crucial for its accessibility.",
        "CorrectAnswer": "Renewable energy sources are growing rapidly but need further investment.",
        "Explanation": "This answer captures both the growth of renewable energy and the need for more investment, which is the focus of the passage.",
        "Hint": "Look for the phrase \"more investment is needed\" to understand the main point."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Advances in biotechnology have allowed scientists to modify crops to be more resistant to pests and diseases. While these genetically modified crops can improve yields and reduce the need for pesticides, concerns about their long-term impact on health and the environment persist.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Genetically modified crops are increasing crop yields and reducing pesticide use.",
        "AnswerChoiceB": "Biotechnology is advancing, but concerns remain about genetically modified crops.",
        "AnswerChoiceC": "Crops modified by biotechnology are more resistant to pests.",
        "AnswerChoiceD": "Pesticides are no longer needed for genetically modified crops.",
        "CorrectAnswer": "Biotechnology is advancing, but concerns remain about genetically modified crops.",
        "Explanation": "This option balances both the advancements and concerns mentioned in the passage, providing a comprehensive summary.",
        "Hint": "Focus on the phrase \"concerns about their long-term impact\" to grasp the full picture."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Urbanization is accelerating around the world, leading to the growth of megacities. While these massive urban areas offer economic opportunities, they also present challenges such as overcrowding, pollution, and inadequate infrastructure.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Megacities offer economic opportunities but face significant challenges.",
        "AnswerChoiceB": "Urbanization is causing pollution and overcrowding in cities.",
        "AnswerChoiceC": "Inadequate infrastructure is a major problem in megacities.",
        "AnswerChoiceD": "Megacities are growing rapidly around the world.",
        "CorrectAnswer": "Megacities offer economic opportunities but face significant challenges.",
        "Explanation": "This captures both the benefits and the challenges of megacities, which is the central focus of the passage.",
        "Hint": "Pay attention to \"economic opportunities\" and \"challenges\" for a balanced understanding."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Artificial intelligence (AI) is transforming industries by automating tasks, improving decision-making, and enhancing productivity. However, the rapid adoption of AI also raises concerns about job displacement and ethical considerations.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "AI is enhancing productivity but raising ethical concerns.",
        "AnswerChoiceB": "AI is transforming industries but also creating challenges.",
        "AnswerChoiceC": "Task automation is a key benefit of AI.",
        "AnswerChoiceD": "AI is leading to job displacement in many industries.",
        "CorrectAnswer": "AI is transforming industries but also creating challenges.",
        "Explanation": "This option summarizes the dual nature of AI’s impact, highlighting both its benefits and its challenges.",
        "Hint": "The contrast between \"transforming industries\" and \"raising concerns\" is key."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Social media has revolutionized the way people communicate and share information. Despite its benefits, such as connecting people globally, it has also been criticized for contributing to the spread of misinformation and encouraging addictive behavior.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Social media has connected people globally but also has negative effects.",
        "AnswerChoiceB": "Misinformation on social media is a growing concern.",
        "AnswerChoiceC": "Addictive behavior is common among social media users.",
        "AnswerChoiceD": "Social media has changed communication in both positive and negative ways.",
        "CorrectAnswer": "Social media has changed communication in both positive and negative ways.",
        "Explanation": "This choice best encapsulates the balanced view of social media's impact presented in the passage.",
        "Hint": "The passage provides both positive and negative effects of social media; keep that in mind when choosing the answer."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The popularity of electric scooters has surged in recent years, providing an eco-friendly and convenient mode of transportation in urban areas. However, cities are struggling to regulate their use, as scooters often cause safety concerns and clutter public spaces.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Cities are struggling to regulate electric scooters due to safety concerns.",
        "AnswerChoiceB": "Electric scooters are growing in popularity but present challenges for cities.",
        "AnswerChoiceC": "Electric scooters are an eco-friendly alternative to cars in urban areas.",
        "AnswerChoiceD": "Regulating the use of electric scooters has become a top priority for cities.",
        "CorrectAnswer": "Electric scooters are growing in popularity but present challenges for cities.",
        "Explanation": "This captures both the benefits of scooters and the challenges they pose for cities, providing a balanced main idea.",
        "Hint": "Look at the phrases \"eco-friendly\" and \"struggling to regulate\" to find the overall message."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Online education has become more widespread, offering students flexible learning opportunities. However, it has also raised concerns about the quality of education and the lack of personal interaction between students and teachers.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Online education offers flexibility but has raised concerns about its quality.",
        "AnswerChoiceB": "Online education is a flexible alternative to traditional learning.",
        "AnswerChoiceC": "Students miss out on personal interaction in online education.",
        "AnswerChoiceD": "The quality of online education is lower than in-person learning.",
        "CorrectAnswer": "Online education offers flexibility but has raised concerns about its quality.",
        "Explanation": "This answer captures both the advantages (flexibility) and concerns (quality) mentioned in the passage.",
        "Hint": "Look at \"flexible learning opportunities\" and \"concerns about quality\" to identify the central idea."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The rise of e-commerce has transformed the retail industry, making it easier for consumers to shop from the comfort of their homes. While this shift has brought convenience, it has also led to the decline of traditional brick-and-mortar stores.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "E-commerce is causing the decline of brick-and-mortar stores.",
        "AnswerChoiceB": "Consumers prefer shopping online due to the convenience of e-commerce.",
        "AnswerChoiceC": "The retail industry is changing as e-commerce grows, leading to both benefits and challenges.",
        "AnswerChoiceD": "E-commerce is replacing traditional stores in many areas.",
        "CorrectAnswer": "The retail industry is changing as e-commerce grows, leading to both benefits and challenges.",
        "Explanation": "This answer highlights both the convenience of e-commerce and the decline of physical stores, reflecting the passage’s dual focus.",
        "Hint": "Look for \"brought convenience\" and \"decline of traditional stores\" to understand the main idea."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Scientific research into climate change has provided overwhelming evidence that human activity is the primary driver of global warming. Despite this, some groups continue to deny the existence of climate change, hindering efforts to address the crisis.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Climate change denial is hindering efforts to address global warming.",
        "AnswerChoiceB": "There is overwhelming evidence that human activity causes climate change.",
        "AnswerChoiceC": "Scientific research is needed to combat climate change denial.",
        "AnswerChoiceD": "Global warming is caused by human activity, but some still deny it.",
        "CorrectAnswer": "Global warming is caused by human activity, but some still deny it.",
        "Explanation": "This answer addresses both the overwhelming evidence for human-caused climate change and the issue of denial, reflecting the passage's main theme.",
        "Hint": "Pay attention to the phrase \"continue to deny\" to understand the challenge presented in the passage."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The introduction of electric buses in cities across the country is part of a larger push to reduce greenhouse gas emissions and promote sustainable transportation. However, the high cost of electric buses has made widespread adoption difficult for many municipalities.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Electric buses are being introduced to reduce emissions, but cost is a barrier to adoption.",
        "AnswerChoiceB": "The high cost of electric buses is preventing their widespread use.",
        "AnswerChoiceC": "Sustainable transportation options are important for reducing emissions.",
        "AnswerChoiceD": "Electric buses are an essential part of reducing greenhouse gas emissions.",
        "CorrectAnswer": "Electric buses are being introduced to reduce emissions, but cost is a barrier to adoption.",
        "Explanation": "This option reflects both the goal of reducing emissions and the challenge posed by the high cost, which are key to the passage.",
        "Hint": "Look for the contrast between \"reduce greenhouse gas emissions\" and \"high cost\" to find the central point."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Genetic testing is becoming increasingly popular, offering individuals insights into their ancestry and health risks. However, some experts warn that the data from these tests could be used by insurance companies and employers in ways that could harm consumers.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Genetic testing offers valuable information but raises concerns about data misuse.",
        "AnswerChoiceB": "Genetic testing is primarily used to determine health risks.",
        "AnswerChoiceC": "Insurance companies could misuse data from genetic tests.",
        "AnswerChoiceD": "Consumers should be cautious about sharing their genetic test results.",
        "CorrectAnswer": "Genetic testing offers valuable information but raises concerns about data misuse.",
        "Explanation": "This captures the dual nature of genetic testing as both informative and potentially harmful, reflecting the passage’s balance.",
        "Hint": "Focus on the contrast between \"insights\" and \"used in ways that could harm\" to grasp the main idea."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Electric car manufacturers are working to extend the driving range of their vehicles to make them more appealing to consumers. Although significant progress has been made, the limited availability of charging stations in many regions remains a barrier to widespread adoption.",
        "Question": "Which choice best states the main idea of the text?",
        "AnswerChoiceA": "Charging station availability is limiting the adoption of electric cars.",
        "AnswerChoiceB": "Electric car manufacturers are extending the range of their vehicles to appeal to consumers.",
        "AnswerChoiceC": "Progress is being made in electric car technology, but charging station access remains a challenge.",
        "AnswerChoiceD": "Consumers want electric cars to have a longer driving range.",
        "CorrectAnswer": "Progress is being made in electric car technology, but charging station access remains a challenge.",
        "Explanation": "This answer reflects the passage's dual focus on improvements in electric cars and the remaining challenges.",
        "Hint": "Look for the phrase \"remains a barrier\" to understand the challenge being discussed."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "As cities grow, urban planners are exploring how green spaces can help reduce air pollution and improve residents' well-being.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Green spaces are becoming harder to maintain in cities.",
        "AnswerChoiceB": "Urban planners are focusing on creating more housing.",
        "AnswerChoiceC": "Cities are expanding without regard for the environment.",
        "AnswerChoiceD": "Green spaces can help reduce pollution and improve well-being.",
        "CorrectAnswer": "Green spaces can help reduce pollution and improve well-being.",
        "Explanation": "The passage emphasizes the role of green spaces in improving city life.",
        "Hint": "Focus on the benefits of green spaces."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Advances in battery technology are key to the future of electric vehicles, as they can improve driving range and reduce charging times.",
        "Question": "What is the main point of the passage?",
        "AnswerChoiceA": "Battery technology will make electric vehicles cheaper to produce.",
        "AnswerChoiceB": "Batteries will soon no longer be needed in electric vehicles.",
        "AnswerChoiceC": "Advances in battery technology will improve range and reduce charging time for EVs.",
        "AnswerChoiceD": "The biggest challenge for electric vehicles is consumer demand.",
        "CorrectAnswer": "Advances in battery technology will improve range and reduce charging time for EVs.",
        "Explanation": "The passage discusses how better batteries will help electric vehicles.",
        "Hint": "Think about the key challenges of EVs and how batteries solve them."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The rise of telemedicine is transforming healthcare, allowing patients to receive medical consultations and treatments from home.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Telemedicine makes in-person medical visits unnecessary.",
        "AnswerChoiceB": "Telemedicine is expanding access to healthcare by offering remote services.",
        "AnswerChoiceC": "Telemedicine is only useful for non-urgent health issues.",
        "AnswerChoiceD": "Most patients prefer in-person visits over telemedicine options.",
        "CorrectAnswer": "Telemedicine is expanding access to healthcare by offering remote services.",
        "Explanation": "The passage focuses on the benefits of telemedicine in expanding access to healthcare.",
        "Hint": "Focus on how telemedicine changes healthcare access."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Space tourism is on the horizon, with private companies racing to develop commercial space travel for everyday consumers.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Space tourism will only be accessible to the wealthy.",
        "AnswerChoiceB": "Commercial space travel is becoming a reality thanks to private companies.",
        "AnswerChoiceC": "Governments are the main drivers behind space tourism.",
        "AnswerChoiceD": "Space tourism will take decades to develop and become mainstream.",
        "CorrectAnswer": "Commercial space travel is becoming a reality thanks to private companies.",
        "Explanation": "The passage discusses the role of private companies in making space tourism a reality.",
        "Hint": "Focus on the role of private companies in developing space tourism."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Scientists have discovered that certain types of algae can be used to create biofuels, offering a sustainable alternative to fossil fuels.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Biofuels made from algae are too costly to produce at scale.",
        "AnswerChoiceB": "Algae-based biofuels are replacing all fossil fuels.",
        "AnswerChoiceC": "Algae can be used to create biofuels as a sustainable alternative to fossil fuels.",
        "AnswerChoiceD": "Fossil fuels remain the best option for large-scale energy production.",
        "CorrectAnswer": "Algae can be used to create biofuels as a sustainable alternative to fossil fuels.",
        "Explanation": "The passage highlights the potential of algae as a biofuel alternative.",
        "Hint": "Focus on algae's role as a sustainable energy source."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Artificial intelligence is being integrated into the legal field, with software helping to analyze legal documents and predict case outcomes.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "AI is replacing lawyers in the courtroom.",
        "AnswerChoiceB": "Artificial intelligence is improving efficiency in the legal field.",
        "AnswerChoiceC": "Legal professionals are resistant to adopting AI technology.",
        "AnswerChoiceD": "AI can only handle basic legal tasks like document review.",
        "CorrectAnswer": "Artificial intelligence is improving efficiency in the legal field.",
        "Explanation": "The passage highlights AI’s role in making legal processes more efficient.",
        "Hint": "Focus on how AI affects the legal profession."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "As the demand for sustainable fashion grows, more designers are creating clothing using recycled materials and eco-friendly production methods.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Fashion brands are struggling to keep up with the demand for eco-friendly clothing.",
        "AnswerChoiceB": "Sustainable fashion is becoming more popular as designers use recycled materials.",
        "AnswerChoiceC": "Clothing made from recycled materials is expensive and inaccessible.",
        "AnswerChoiceD": "The fashion industry is largely unaffected by sustainability concerns.",
        "CorrectAnswer": "Sustainable fashion is becoming more popular as designers use recycled materials.",
        "Explanation": "The passage emphasizes the shift toward eco-friendly fashion.",
        "Hint": "Focus on the growth of sustainable fashion."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Genetic testing is providing individuals with valuable insights into their ancestry and potential health risks, leading to more personalized healthcare.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Genetic testing can only reveal ancestry information.",
        "AnswerChoiceB": "Personalized healthcare is the future of medicine.",
        "AnswerChoiceC": "Genetic testing is offering insights into ancestry and health risks for personalized care.",
        "AnswerChoiceD": "Genetic testing has many ethical concerns that outweigh its benefits.",
        "CorrectAnswer": "Genetic testing is offering insights into ancestry and health risks for personalized care.",
        "Explanation": "The passage discusses how genetic testing is shaping personalized healthcare.",
        "Hint": "Focus on the dual benefits of genetic testing."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Electric bicycles, or e-bikes, are growing in popularity as a convenient and eco-friendly mode of transportation in urban areas.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "E-bikes are a passing trend that will soon decline.",
        "AnswerChoiceB": "Electric bicycles are becoming popular for their convenience and environmental benefits.",
        "AnswerChoiceC": "Most cities do not allow the use of electric bicycles on public roads.",
        "AnswerChoiceD": "E-bikes are too expensive for widespread adoption.",
        "CorrectAnswer": "Electric bicycles are becoming popular for their convenience and environmental benefits.",
        "Explanation": "The passage focuses on how e-bikes are gaining popularity in cities.",
        "Hint": "Focus on the rise of e-bikes as a transportation option."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The use of drones in agriculture is increasing, helping farmers monitor crops, apply fertilizers, and reduce labor costs.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Drones are replacing traditional farming methods entirely.",
        "AnswerChoiceB": "Drones are only useful for monitoring large farms.",
        "AnswerChoiceC": "Drones are improving agricultural efficiency by reducing labor and monitoring crops.",
        "AnswerChoiceD": "Farming practices are unlikely to change significantly with drone technology.",
        "CorrectAnswer": "Drones are improving agricultural efficiency by reducing labor and monitoring crops.",
        "Explanation": "The passage discusses how drones are making farming more efficient.",
        "Hint": "Focus on how drones benefit farming."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Autonomous delivery robots are being tested in urban areas, offering a glimpse into the future of contactless deliveries.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Delivery robots are unreliable and inefficient.",
        "AnswerChoiceB": "Autonomous robots will eventually replace all delivery services.",
        "AnswerChoiceC": "Autonomous delivery robots are being tested to improve contactless delivery services.",
        "AnswerChoiceD": "Delivery robots are only effective in suburban areas.",
        "CorrectAnswer": "Autonomous delivery robots are being tested to improve contactless delivery services.",
        "Explanation": "The passage emphasizes how delivery robots are shaping the future of delivery services.",
        "Hint": "Focus on the future of contactless deliveries."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Electric vehicle (EV) charging stations are becoming more widespread, with governments and private companies investing in infrastructure to support EV growth.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Charging infrastructure for EVs is growing, but progress is slow.",
        "AnswerChoiceB": "EV charging stations are becoming more common as governments and companies invest in them.",
        "AnswerChoiceC": "Electric vehicles are declining in popularity despite the growth in charging stations.",
        "AnswerChoiceD": "EV charging stations will eventually replace all gas stations.",
        "CorrectAnswer": "EV charging stations are becoming more common as governments and companies invest in them.",
        "Explanation": "The passage focuses on the growing investment in EV charging infrastructure.",
        "Hint": "Focus on the growth of EV charging networks."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "The development of self-healing materials could revolutionize industries by creating products that can repair themselves after damage.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Self-healing materials are too expensive to be used widely.",
        "AnswerChoiceB": "Industries are adopting self-healing materials for more durable products.",
        "AnswerChoiceC": "Self-healing materials have limited applications in industries.",
        "AnswerChoiceD": "The development of self-healing materials could change the future of many industries.",
        "CorrectAnswer": "The development of self-healing materials could change the future of many industries.",
        "Explanation": "The passage emphasizes the potential impact of self-healing materials.",
        "Hint": "Focus on the broad implications of self-healing technology."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Smart home devices are becoming more advanced, allowing homeowners to control lighting, security, and appliances from their smartphones.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Smart home devices are too complex for everyday users.",
        "AnswerChoiceB": "Homeowners are reluctant to adopt smart home technology.",
        "AnswerChoiceC": "Smart home devices offer convenience by allowing control of various home functions through smartphones.",
        "AnswerChoiceD": "Most smart home devices only control lighting and security.",
        "CorrectAnswer": "Smart home devices offer convenience by allowing control of various home functions through smartphones.",
        "Explanation": "The passage focuses on the convenience of smart home technology.",
        "Hint": "Focus on how smart homes offer control and convenience."
    },
    {
        "TypeofQuestion": "Main Idea",
        "Passage": "Virtual reality (VR) is being used in education to create immersive learning experiences, allowing students to explore historical events or scientific concepts in 3D environments.",
        "Question": "What is the main idea of the passage?",
        "AnswerChoiceA": "Virtual reality is replacing traditional classroom teaching.",
        "AnswerChoiceB": "VR is being used to enhance learning experiences in education.",
        "AnswerChoiceC": "Students find virtual reality too distracting for educational purposes.",
        "AnswerChoiceD": "Virtual reality is primarily used for entertainment rather than education.",
        "CorrectAnswer": "VR is being used to enhance learning experiences in education.",
        "Explanation": "The passage emphasizes the use of VR to improve education.",
        "Hint": "Focus on how VR enhances learning."
    }
]

let arrWordsInContextQues = [
    {
         "TypeofQuestion": "Words in Context",
        "Passage": "The chef’s signature dish was ______ with delicate spices and herbs, giving it a flavor that lingered long after the last bite.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "marinated",
        "AnswerChoiceB": "cooked",
        "AnswerChoiceC": "bathed",
        "AnswerChoiceD": "infused",
        "CorrectAnswer": "infused",
        "Explanation": "Infused best captures the idea of flavors being subtly introduced into the dish, whereas \"cooked\" and \"bathed\" are less precise in this context.",
        "Hint": "Focus on \"delicate spices and herbs,\" which suggests the process of infusing flavor."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "During the final stage of construction, the building’s structure was ______ to ensure it met all safety standards before opening to the public.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "modified",
        "AnswerChoiceB": "tested",
        "AnswerChoiceC": "evaluated",
        "AnswerChoiceD": "adjusted",
        "CorrectAnswer": "evaluated",
        "Explanation": "Evaluated best fits the context of making sure the building meets safety standards, which involves assessment, not just testing or adjusting.",
        "Hint": "Look for the word that aligns with the idea of checking or assessing the building’s safety."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "The artist’s painting, which had previously been dismissed as overly simplistic, was suddenly ______ by critics after its inclusion in a major gallery exhibition.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "rejected",
        "AnswerChoiceB": "examined",
        "AnswerChoiceC": "revered",
        "AnswerChoiceD": "reconsidered",
        "CorrectAnswer": "reconsidered",
        "Explanation": "Reconsidered fits the passage’s context of changing opinions, as the painting was originally dismissed but is now seen in a new light.",
        "Hint": "Pay attention to \"dismissed\" and think about how opinions have shifted."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "The politician’s speech was filled with ______ language, meant to inspire confidence in the public but offering little in terms of actual policy.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "rhetorical",
        "AnswerChoiceB": "specific",
        "AnswerChoiceC": "unintelligible",
        "AnswerChoiceD": "descriptive",
        "CorrectAnswer": "rhetorical",
        "Explanation": "Rhetorical refers to language used to persuade or influence rather than to convey concrete details, which matches the vague nature of the speech.",
        "Hint": "Focus on \"meant to inspire confidence\" to understand the tone and intent of the speech."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "Despite their many attempts to defeat the competition, the team remained ______, determined to succeed in the face of adversity.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "doubtful",
        "AnswerChoiceB": "confident",
        "AnswerChoiceC": "relentless",
        "AnswerChoiceD": "apathetic",
        "CorrectAnswer": "relentless",
        "Explanation": "Relentless suggests persistence and determination, which aligns with the team's attitude toward overcoming adversity.",
        "Hint": "Look at the phrase \"determined to succeed\" for a clue about the team's mindset."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "The new manager quickly made changes to streamline the company’s operations, ______ unnecessary procedures and implementing more efficient ones.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "creating",
        "AnswerChoiceB": "replacing",
        "AnswerChoiceC": "eliminating",
        "AnswerChoiceD": "simplifying",
        "CorrectAnswer": "eliminating",
        "Explanation": "Eliminating best fits the context of removing unnecessary procedures to improve efficiency, as \"creating\" or \"replacing\" wouldn’t make sense here.",
        "Hint": "Focus on \"unnecessary procedures\" to find the word that suggests removal."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "His excitement about the opportunity was ______ by his nervousness, as he had never given a speech to such a large audience before.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "matched",
        "AnswerChoiceB": "diminished",
        "AnswerChoiceC": "exaggerated",
        "AnswerChoiceD": "heightened",
        "CorrectAnswer": "diminished",
        "Explanation": "Diminished fits best because his nervousness took away from his excitement, making it less intense.",
        "Hint": "Look at the contrast between \"excitement\" and \"nervousness\" to find the answer."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "Her interpretation of the novel was ______, focusing on the complexities of the characters' relationships rather than the overarching themes.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "insightful",
        "AnswerChoiceB": "surface-level",
        "AnswerChoiceC": "narrow",
        "AnswerChoiceD": "convoluted",
        "CorrectAnswer": "narrow",
        "Explanation": "Narrow suggests that her focus was limited to one aspect of the novel, which is implied by the specific focus on characters' relationships.",
        "Hint": "Focus on the phrase \"focusing on the complexities\" to determine how her interpretation was restricted."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "The company’s decision to switch to renewable energy sources was ______ by environmental advocates, who saw it as a major step toward sustainability.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "criticized",
        "AnswerChoiceB": "applauded",
        "AnswerChoiceC": "questioned",
        "AnswerChoiceD": "ignored",
        "CorrectAnswer": "applauded",
        "Explanation": "Applauded makes the most sense because environmental advocates would likely praise a decision that promotes sustainability.",
        "Hint": "Pay attention to \"environmental advocates\" to determine their likely reaction to the company’s decision."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "Their friendship grew stronger after they ______ their differences and focused on the things they had in common.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "discussed",
        "AnswerChoiceB": "ignored",
        "AnswerChoiceC": "overcame",
        "AnswerChoiceD": "embraced",
        "CorrectAnswer": "overcame",
        "Explanation": "Overcame fits because the friends needed to get past their differences to strengthen their relationship, not just ignore them.",
        "Hint": "Look for the word that implies resolving an issue rather than avoiding it."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "The scientist’s findings were ______ by her colleagues, who recognized the groundbreaking nature of her work and its potential implications.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "praised",
        "AnswerChoiceB": "scrutinized",
        "AnswerChoiceC": "dismissed",
        "AnswerChoiceD": "revised",
        "CorrectAnswer": "praised",
        "Explanation": "Praised is the best choice since the passage suggests her colleagues saw her work as groundbreaking, implying positive feedback.",
        "Hint": "Focus on the word \"recognized\" to understand that her work was acknowledged positively."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "The marathon runner’s endurance was truly ______, as he pushed through extreme fatigue to finish the race.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "admirable",
        "AnswerChoiceB": "questionable",
        "AnswerChoiceC": "disappointing",
        "AnswerChoiceD": "incredible",
        "CorrectAnswer": "incredible",
        "Explanation": "Incredible fits best, as the passage describes the runner overcoming extreme fatigue, suggesting a remarkable feat.",
        "Hint": "Pay attention to \"pushed through extreme fatigue\" to find the word that describes an extraordinary effort."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "The scientist was ______ in her approach, carefully considering all possible outcomes before making a decision.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "impatient",
        "AnswerChoiceB": "methodical",
        "AnswerChoiceC": "impulsive",
        "AnswerChoiceD": "careless",
        "CorrectAnswer": "methodical",
        "Explanation": "Methodical best describes someone who takes a careful and organized approach, fitting with the idea of considering all outcomes.",
        "Hint": "Look at \"carefully considering all possible outcomes\" to find the word that suggests thoroughness."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "Her artistic style was ______ by a combination of modern techniques and traditional influences, resulting in a unique fusion of the old and the new.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "defined",
        "AnswerChoiceB": "obscured",
        "AnswerChoiceC": "inspired",
        "AnswerChoiceD": "altered",
        "CorrectAnswer": "inspired",
        "Explanation": "Inspired fits the context of her style being shaped by different influences, as opposed to being defined or altered.",
        "Hint": "Focus on \"a combination of modern techniques and traditional influences\" to guide you to the answer."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "Although the witness’s testimony seemed ______ at first, further investigation revealed several inconsistencies in the story.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "accurate",
        "AnswerChoiceB": "convincing",
        "AnswerChoiceC": "unreliable",
        "AnswerChoiceD": "questionable",
        "CorrectAnswer": "convincing",
        "Explanation": "Convincing is the correct choice because the testimony initially seemed believable, though inconsistencies later emerged.",
        "Hint": "Pay attention to \"seemed\" to understand that the testimony initially appeared valid."
    },
    {
        "TypeofQuestion": "Words in Context",
        "Passage": "Despite the intense competition, the young athlete remained ______, focused solely on improving her personal best rather than on the achievements of others.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "unmotivated",
        "AnswerChoiceB": "determined",
        "AnswerChoiceC": "indifferent",
        "AnswerChoiceD": "competitive",
        "CorrectAnswer": "determined",
        "Explanation": "Determined best fits the context of staying focused on personal improvement despite competition.",
        "Hint": "Look at the phrase \"focused solely on improving her personal best\" to understand her mindset."
    },
    {
        "TypeOfQuestion": "Words in Context",
        "Passage": "The news article was filled with ______ claims, making it difficult for readers to determine what was fact and what was speculation.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "unsupported",
        "AnswerChoiceB": "verified",
        "AnswerChoiceC": "accurate",
        "AnswerChoiceD": "detailed",
        "CorrectAnswer": "unsupported",
        "Explanation": "Unsupported best describes claims that lack evidence, making it hard for readers to trust the information.",
        "Hint": "Focus on \"making it difficult for readers to determine\" to guide you toward the correct word."
    },
    {
        "TypeOfQuestion": "Words in Context",
        "Passage": "The lawyer’s argument was ______ by new evidence that directly contradicted the key points of his case.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "strengthened",
        "AnswerChoiceB": "weakened",
        "AnswerChoiceC": "justified",
        "AnswerChoiceD": "reinforced",
        "CorrectAnswer": "weakened",
        "Explanation": "Weakened fits best because the new evidence directly contradicted the lawyer's case, undermining his argument.",
        "Hint": "Look for the word that aligns with \"contradicted\" to find the answer."
    },
    {
        "TypeOfQuestion": "Words in Context",
        "Passage": "The community garden project was ______ by local volunteers, who provided both financial support and labor to help it succeed.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "opposed",
        "AnswerChoiceB": "abandoned",
        "AnswerChoiceC": "supported",
        "AnswerChoiceD": "ignored",
        "CorrectAnswer": "supported",
        "Explanation": "Supported is the best choice because the volunteers helped the project with both money and effort.",
        "Hint": "Focus on \"provided both financial support and labor\" to find the answer that describes positive involvement."
    },
    {
        "TypeOfQuestion": "Words in Context",
        "Passage": "The decision to close the factory was made after a ______ analysis of the company’s financial situation, which revealed unsustainable losses.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "detailed",
        "AnswerChoiceB": "brief",
        "AnswerChoiceC": "cursory",
        "AnswerChoiceD": "simple",
        "CorrectAnswer": "detailed",
        "Explanation": "Detailed best fits the context of a thorough examination of the company’s finances, leading to the decision to close.",
        "Hint": "Pay attention to \"revealed unsustainable losses\" to understand that a deep analysis was required."
    }

]


let arrComparingPassages = [
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1: Some scientists argue that artificial intelligence (AI) poses risks to employment. They claim that as AI becomes more capable, it will replace humans in many jobs, leading to widespread unemployment.<br><br>Passage 2: Other researchers, however, believe that AI will create new jobs in industries that don’t exist yet. They argue that while some jobs will disappear, new ones will be created to balance the losses.",
        "Question": "Based on the texts, both Passage 1 and Passage 2 would most likely agree with which statement?",
        "AnswerChoiceA": "AI will lead to mass unemployment across all industries.",
        "AnswerChoiceB": "AI will create new industries that don’t currently exist.",
        "AnswerChoiceC": "AI will impact employment by both eliminating and creating jobs.",
        "AnswerChoiceD": "AI will have little effect on the job market in the future.",
        "CorrectAnswer": "AI will impact employment by both eliminating and creating jobs.",
        "Explanation": "Both passages agree that AI will have effects on employment, but they differ on whether it will be positive or negative overall.",
        "Hint": "Focus on how both passages discuss job creation and elimination."
    },
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1: Some historians argue that the collapse of the Roman Empire was primarily due to external invasions by barbarian tribes. <br><br> Passage 2: Other historians contend that the Roman Empire fell because of internal political corruption and economic instability, which weakened the state before any external invasion.",
        "Question": "How would the historians in Passage 2 most likely respond to the argument made in Passage 1?",
        "AnswerChoiceA": "By agreeing that external invasions were the sole cause of the collapse",
        "AnswerChoiceB": "By arguing that external invasions were a symptom of internal weakness",
        "AnswerChoiceC": "By denying that invasions had any role in the empire’s fall",
        "AnswerChoiceD": "By asserting that the collapse was inevitable regardless of invasions",
        "CorrectAnswer": "By arguing that external invasions were a symptom of internal weakness",
        "Explanation": "Passage 2 emphasizes internal causes of Rome's collapse, suggesting that invasions took advantage of pre-existing weaknesses.",
        "Hint": "Look at how Passage 2 frames the relationship between internal and external factors."
    },
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1: Green energy initiatives have greatly reduced carbon emissions in some countries, showing that a shift away from fossil fuels is possible. <br><br>Passage 2: Despite green energy efforts, some argue that fossil fuels will continue to be essential for many years due to their affordability and availability.",
        "Question": "What would both Passage 1 and Passage 2 likely agree on?",
        "AnswerChoiceA": "Fossil fuels should be phased out immediately.",
        "AnswerChoiceB": "Green energy is the only solution to climate change.",
        "AnswerChoiceC": "Fossil fuels will play a role in the energy landscape for the foreseeable future.",
        "AnswerChoiceD": "Green energy can replace fossil fuels completely in the next decade.",
        "CorrectAnswer": "Fossil fuels will play a role in the energy landscape for the foreseeable future.",
        "Explanation": "Both passages suggest that fossil fuels still have a role to play, even with the growth of green energy.",
        "Hint": "Focus on how both passages acknowledge the current state of fossil fuel use."
    },
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1: Online education is becoming more popular due to its convenience, but critics argue it lacks the personal interaction of traditional classrooms. <br><br> Passage 2: Supporters of online education point to advancements in technology, like virtual reality, that allow for more interactive experiences, making online learning increasingly immersive.",
        "Question": "Based on the texts, how would the author of Passage 2 most likely respond to the concerns in Passage 1?",
        "AnswerChoiceA": "By agreeing that online education lacks personal interaction",
        "AnswerChoiceB": "By arguing that technology is improving online education’s interactive capabilities",
        "AnswerChoiceC": "By stating that online education is no substitute for in-person classes",
        "AnswerChoiceD": "By suggesting that online education will eventually replace traditional classrooms",
        "CorrectAnswer": "By arguing that technology is improving online education’s interactive capabilities",
        "Explanation": "Passage 2 focuses on how technology can address the lack of interaction mentioned in Passage 1.",
        "Hint": "Consider how Passage 2 views technology's role in improving online learning."
    },
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1:Climate scientists argue that a rise in global temperatures will increase the frequency of natural disasters such as hurricanes and droughts, disrupting ecosystems and human communities.<br><br> Passage 2:Economists emphasize that, while climate change may have some negative effects, it also presents opportunities for innovation in energy and agriculture. For example, drought-resistant crops could be developed, and renewable energy sources could become more competitive in the market.",
        "Question": "Based on the texts, how would the economists in Passage 2 most likely respond to the concerns raised by the scientists in Passage 1?",
        "AnswerChoiceA": "They would agree that climate change presents more risks than benefits.",
        "AnswerChoiceB": "They would acknowledge the risks but emphasize the potential for economic and technological innovation.",
        "AnswerChoiceC": "They would argue that natural disasters are not as serious as the scientists claim.",
        "AnswerChoiceD": "They would propose abandoning efforts to combat climate change in favor of economic growth.",
        "CorrectAnswer": "They would acknowledge the risks but emphasize the potential for economic and technological innovation.",
        "Explanation": "The economists in Passage 2 recognize the risks but focus on the opportunities climate change presents, unlike the scientists in Passage 1, who focus on the dangers.",
        "Hint": "Look for where Passage 2 discusses opportunities alongside risks."
    },
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1:The philosopher argues that humans act based on free will, which is driven by their ability to make moral choices independent of external influence. <br><br> Passage 2: A neuroscientist contends that human behavior is largely determined by biological processes in the brain, leaving little room for free will. According to the neuroscientist, the perception of free will is an illusion created by neural activity.",
        "Question": "Based on the texts, how would the philosopher in Passage 1 most likely respond to the argument of the neuroscientist in Passage 2?",
        "AnswerChoiceA": "The philosopher would argue that free will is incompatible with any biological processes.",
        "AnswerChoiceB": "The philosopher would agree that free will is an illusion created by the brain.",
        "AnswerChoiceC": "The philosopher would assert that moral choices can be made regardless of biological influences.",
        "AnswerChoiceD": "The philosopher would argue that the brain is solely responsible for human actions.",
        "CorrectAnswer": "The philosopher would assert that moral choices can be made regardless of biological influences.",
        "Explanation": "The philosopher believes in free will, even in the presence of biological influences, while the neuroscientist denies it.",
        "Hint": "Focus on the difference between moral choices and biological determinism."
    },
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1:Historian A argues that the Industrial Revolution was driven by technological innovation, which allowed for unprecedented productivity and economic growth in the 19th century. <br><br>Passage 2:Historian B suggests that the Industrial Revolution was a product of social and political changes, such as the rise of capitalism and shifts in labor systems, rather than purely technological factors.",
        "Question": "Based on the texts, how would Historian B most likely respond to Historian A’s perspective?",
        "AnswerChoiceA": "Historian B would argue that technological innovation was irrelevant to the Industrial Revolution.",
        "AnswerChoiceB": "Historian B would agree that technology played a role but emphasize that social and political factors were more important.",
        "AnswerChoiceC": "Historian B would assert that capitalism hindered, rather than helped, the Industrial Revolution.",
        "AnswerChoiceD": "Historian B would claim that the Industrial Revolution was driven by economic, not social, changes.",
        "CorrectAnswer": "Historian B would agree that technology played a role but emphasize that social and political factors were more important.",
        "Explanation": "Historian B acknowledges technological innovation but views social and political changes as more critical to the Industrial Revolution.",
        "Hint": "Look for how Passage 2 addresses factors beyond technology."
    },
    {
        "TypeofQuestion": "Compare Passages",
        "Passage": "Passage 1:According to Dr. Smith, the rise of antibiotic-resistant bacteria is due to the overuse of antibiotics in medical treatments and agricultural practices. These \"superbugs\" pose a significant threat to public health. <br><br>Passage 2:Dr. Patel argues that the rise of antibiotic resistance can be mitigated through the development of new drugs and the improvement of diagnostic tools. Patel believes that with the right advancements, the threat of superbugs can be minimized.",
        "Question": "Based on the texts, what is the main difference between Dr. Smith’s and Dr. Patel’s perspectives on antibiotic resistance?",
        "AnswerChoiceA": "Dr. Smith believes antibiotic resistance is not a serious threat, while Dr. Patel disagrees.",
        "AnswerChoiceB": "Dr. Patel is optimistic that new medical technologies can address antibiotic resistance, while Dr. Smith focuses on the risks posed by current practices.",
        "AnswerChoiceC": "Dr. Smith believes new drugs are the key to addressing antibiotic resistance, while Dr. Patel believes in limiting antibiotic use.",
        "AnswerChoiceD": "Both Dr. Smith and Dr. Patel agree that antibiotic resistance cannot be controlled.",
        "CorrectAnswer": "Dr. Patel is optimistic that new medical technologies can address antibiotic resistance, while Dr. Smith focuses on the risks posed by current practices.",
        "Explanation": "Dr. Patel sees technological advancements as a solution, while Dr. Smith emphasizes the dangers of current practices.",
        "Hint": "Focus on their differing views on technological solutions."
    }
]



let arrStandardEnglishConventions= [
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Running late, the student ______________.",
        "Question": "Choose the option that completes the sentence logically.",
        "AnswerChoiceA": "the class ended.",
        "AnswerChoiceB": "rushed to catch the bus.",
        "AnswerChoiceC": "left the assignment unfinished.",
        "AnswerChoiceD": "sat quietly in the back.",
        "CorrectAnswer": "rushed to catch the bus.",
        "Explanation": "This completes the sentence with a logical and grammatically correct phrase that describes what the student did while running late.",
        "Hint": "Think about what someone might do when running late."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "She enjoys reading novels, watching movies, and __________.",
        "Question": "Choose the word that best maintains parallel structure.",
        "AnswerChoiceA": "to swim.",
        "AnswerChoiceB": "swimming.",
        "AnswerChoiceC": "swims.",
        "AnswerChoiceD": "having swum.",
        "CorrectAnswer": "swimming.",
        "Explanation": "The sentence contains a list of verbs in gerund form (\"-ing\"), so \"swimming\" maintains this structure.",
        "Hint": "Look for consistent verb forms within a list."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Driving through the city, __________.",
        "Question": "Choose the best option to complete the sentence while keeping the modifier in the correct position.",
        "AnswerChoiceA": "the skyscrapers could be seen towering above.",
        "AnswerChoiceB": "we passed several tall buildings.",
        "AnswerChoiceC": "the buildings loomed overhead.",
        "AnswerChoiceD": "you can see tall skyscrapers.",
        "CorrectAnswer": "we passed several tall buildings.",
        "Explanation": "The modifier \"Driving through the city\" should be followed by the subject that actually did the driving, so \"we\" is appropriate here.",
        "Hint": "Focus on who is doing the driving."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "He ______________ for his exam last week, but today he ______________ the results.",
        "Question": "Select the pair of verbs that maintain consistent tense.",
        "AnswerChoiceA": "studied, waits",
        "AnswerChoiceB": "studies, is waiting",
        "AnswerChoiceC": "studied, is waiting",
        "AnswerChoiceD": "studies, waited",
        "CorrectAnswer": "studied, is waiting",
        "Explanation": "The past tense \"studied\" aligns with \"last week,\" and the present continuous \"is waiting\" aligns with \"today.\"",
        "Hint": "Look for a past event and something happening today."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Whenever the students completed their projects, __________ turned them in.",
        "Question": "Choose the correct pronoun to complete the sentence.",
        "AnswerChoiceA": "he",
        "AnswerChoiceB": "them",
        "AnswerChoiceC": "they",
        "AnswerChoiceD": "it",
        "CorrectAnswer": "they",
        "Explanation": "The pronoun \"they\" correctly refers to the plural noun \"students.\"",
        "Hint": "Ensure the pronoun matches the subject in number and gender."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "By the time the meeting started, everyone in the room __________.",
        "Question": "Choose the phrase that correctly completes the sentence.",
        "AnswerChoiceA": "had already left.",
        "AnswerChoiceB": "was leaving.",
        "AnswerChoiceC": "had been leaving.",
        "AnswerChoiceD": "leaves.",
        "CorrectAnswer": "had already left.",
        "Explanation": "Had already left",
        "Hint": "Look for clues indicating the timeline of events."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "The job requires attention to detail, excellent communication skills, and __________.",
        "Question": "Choose the phrase that best completes the list while maintaining parallel structure.",
        "AnswerChoiceA": "being able to meet deadlines.",
        "AnswerChoiceB": "meeting deadlines.",
        "AnswerChoiceC": "to meet deadlines.",
        "AnswerChoiceD": "having met deadlines.",
        "CorrectAnswer": "meeting deadlines.",
        "Explanation": "Meeting deadlines",
        "Hint": "Match the form of the earlier list items."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "After eating a large meal, __________.",
        "Question": "Choose the sentence that correctly places the modifier.",
        "AnswerChoiceA": "the nap was necessary.",
        "AnswerChoiceB": "we decided to take a nap.",
        "AnswerChoiceC": "it was time for a nap.",
        "AnswerChoiceD": "a nap was needed.",
        "CorrectAnswer": "we decided to take a nap.",
        "Explanation": "The modifier \"After eating a large meal\" should logically apply to \"we,\" the ones who ate the meal and decided to nap.",
        "Hint": "Think about who took the action."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "As soon as she __________, she will __________ the results.",
        "Question": "Select the pair of verbs that maintain consistent tense.",
        "AnswerChoiceA": "arrives, checks",
        "AnswerChoiceB": "arrived, checking",
        "AnswerChoiceC": "arrives, checked",
        "AnswerChoiceD": "arriving, check",
        "CorrectAnswer": "arrives, checks",
        "Explanation": "Both verbs should be in the future form to indicate something that will happen once she arrives and checks the results.",
        "Hint": "Focus on actions that will occur in the future."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Neither John nor his friends wanted to give up __________ spot in line.",
        "Question": "Choose the correct pronoun to complete the sentence.",
        "AnswerChoiceA": "his",
        "AnswerChoiceB": "their",
        "AnswerChoiceC": "its",
        "AnswerChoiceD": "he's",
        "CorrectAnswer": "their",
        "Explanation": "Since \"friends\" is plural, the correct pronoun is \"their.\"",
        "Hint": "Look for the pronoun that matches the plural subject."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "The sun was setting, and the sky __________.",
        "Question": "Choose the option that completes the sentence logically.",
        "AnswerChoiceA": "turned a bright shade of pink.",
        "AnswerChoiceB": "is turning darker.",
        "AnswerChoiceC": "becomes a deep blue.",
        "AnswerChoiceD": "would be glowing.",
        "CorrectAnswer": "turned a bright shade of pink.",
        "Explanation": "The verb \"turned\" matches the past tense context of the sentence.",
        "Hint": "Consider the verb tense used earlier in the sentence."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "The workshop was focused on designing, planning, and __________.",
        "Question": "Choose the phrase that completes the list while maintaining parallel structure.",
        "AnswerChoiceA": "to execute.",
        "AnswerChoiceB": "execution.",
        "AnswerChoiceC": "executing.",
        "AnswerChoiceD": "to be executed.",
        "CorrectAnswer": "executing.",
        "Explanation": "The phrase \"executing\" matches the gerund form of the earlier verbs in the list.",
        "Hint": "Look for consistency in the action verbs."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "While cleaning the house, __________.",
        "Question": "Choose the option that correctly places the modifier.",
        "AnswerChoiceA": "the vacuum broke.",
        "AnswerChoiceB": "we accidentally broke the vacuum.",
        "AnswerChoiceC": "a loud noise was heard.",
        "AnswerChoiceD": "it was difficult to clean.",
        "CorrectAnswer": "we accidentally broke the vacuum.",
        "Explanation": "The modifier \"While cleaning the house\" should be followed by the subject \"we,\" as \"we\" did the cleaning and broke the vacuum.",
        "Hint": "Focus on who did the cleaning."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Last summer, they __________ to the beach every weekend and __________ swimming.",
        "Question": "Choose the verbs that maintain tense consistency.",
        "AnswerChoiceA": "go, enjoy",
        "AnswerChoiceB": "went, enjoyed",
        "AnswerChoiceC": "go, enjoying",
        "AnswerChoiceD": "went, enjoying",
        "CorrectAnswer": "went, enjoyed",
        "Explanation": "Both verbs need to be in the past tense to maintain consistency with \"last summer.\"",
        "Hint": "Ensure the past tense matches the time frame."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Each student should bring __________ own pencil to the exam.",
        "Question": "Choose the correct pronoun to complete the sentence.",
        "AnswerChoiceA": "his or her",
        "AnswerChoiceB": "their",
        "AnswerChoiceC": "its",
        "AnswerChoiceD": "their or hers",
        "CorrectAnswer": "his or her",
        "Explanation": "Since \"Each student\" is singular, the pronoun must be singular (\"his or her\").",
        "Hint": "Look for agreement between the subject and pronoun."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "By the time the train arrived, we __________.",
        "Question": "Choose the phrase that correctly completes the sentence.",
        "AnswerChoiceA": "had been waiting for hours.",
        "AnswerChoiceB": "will be waiting.",
        "AnswerChoiceC": "have waited.",
        "AnswerChoiceD": "are waiting.",
        "CorrectAnswer": "had been waiting for hours.",
        "Explanation": "Had been waiting",
        "Hint": "Look for verb tense indicating an earlier action."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Her hobbies include painting, drawing, and __________.",
        "Question": "Choose the phrase that maintains parallel structure.",
        "AnswerChoiceA": "to sing.",
        "AnswerChoiceB": "singing.",
        "AnswerChoiceC": "sings.",
        "AnswerChoiceD": "having sung.",
        "CorrectAnswer": "singing.",
        "Explanation": "The gerund \"singing\" matches the parallel structure of the other hobbies listed.",
        "Hint": "Keep the form consistent with the other hobbies."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "As we walked through the park, __________.",
        "Question": "Choose the phrase that correctly places the modifier.",
        "AnswerChoiceA": "the flowers were blooming beautifully.",
        "AnswerChoiceB": "beautiful flowers bloomed.",
        "AnswerChoiceC": "we admired the blooming flowers.",
        "AnswerChoiceD": "a beautiful scene unfolded.",
        "CorrectAnswer": "we admired the blooming flowers.",
        "Explanation": "The subject \"we\" correctly matches the action of walking and admiring the flowers.",
        "Hint": "Think about who did the admiring."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Tomorrow, they __________ to start the project and __________ everything by Friday.",
        "Question": "Select the verbs that maintain future tense consistency.",
        "AnswerChoiceA": "plan, finish",
        "AnswerChoiceB": "planned, finished",
        "AnswerChoiceC": "plans, finish",
        "AnswerChoiceD": "planning, finishes",
        "CorrectAnswer": "plan, finish",
        "Explanation": "Both verbs are in the future tense, which aligns with the context of \"tomorrow\" and \"by Friday.\"",
        "Hint": "Ensure the future tense is consistent throughout."
    },
    {
        "TypeofQuestion": "Standard English Conventions",
        "Passage": "Neither the cat nor the dog likes __________ new food.",
        "Question": "Choose the correct pronoun to complete the sentence.",
        "AnswerChoiceA": "his",
        "AnswerChoiceB": "their",
        "AnswerChoiceC": "its",
        "AnswerChoiceD": "they're",
        "CorrectAnswer": "its",
        "Explanation": "Dog",
        "Hint": "Look for agreement with the singular subject \"dog.\""
    }
]


let arrTransition = [
    {
        "TypeofQuestion": "Transition",
        "Passage": "The project faced many setbacks in its initial phase. __________, the team managed to deliver it on time.",
        "Question": "Which choice completes the text with the most logical and precise word?",
        "AnswerChoiceA": "However",
        "AnswerChoiceB": "Therefore",
        "AnswerChoiceC": "Similarly",
        "AnswerChoiceD": "Because",
        "CorrectAnswer": "However",
        "Explanation": "The sentence contrasts setbacks with success, making \"However\" the best choice.",
        "Hint": "Look for contrast words."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The experiment yielded some surprising results. __________, more studies are needed to confirm the findings.",
        "Question": "Which choice completes the text logically?",
        "AnswerChoiceA": "As a result",
        "AnswerChoiceB": "For example",
        "AnswerChoiceC": "Nevertheless",
        "AnswerChoiceD": "Therefore",
        "CorrectAnswer": "Nevertheless",
        "Explanation": "The sentence introduces a contrast between results and the need for more studies, making \"Nevertheless\" the best choice.",
        "Hint": "Pay attention to contrast clues."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The company has a solid reputation for innovation. __________, its latest product has received mixed reviews.",
        "Question": "Which choice best completes the text?",
        "AnswerChoiceA": "Similarly",
        "AnswerChoiceB": "Yet",
        "AnswerChoiceC": "On the other hand",
        "AnswerChoiceD": "Additionally",
        "CorrectAnswer": "On the other hand",
        "Explanation": "The second sentence presents a contrasting point, making \"On the other hand\" the most logical choice.",
        "Hint": "Focus on contrasting information."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The proposal was ambitious, aiming to restructure the entire department. __________, it required significant changes to current operations.",
        "Question": "Which word completes the text logically?",
        "AnswerChoiceA": "In contrast",
        "AnswerChoiceB": "Consequently",
        "AnswerChoiceC": "Likewise",
        "AnswerChoiceD": "As a result",
        "CorrectAnswer": "As a result",
        "Explanation": "As a result",
        "Hint": "Look for a cause-effect relationship."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The meal was delicious. __________, the service was extremely slow.",
        "Question": "Which transition best completes the text?",
        "AnswerChoiceA": "Meanwhile",
        "AnswerChoiceB": "However",
        "AnswerChoiceC": "In addition",
        "AnswerChoiceD": "For instance",
        "CorrectAnswer": "However",
        "Explanation": "However",
        "Hint": "Focus on the contrast between two aspects of the dining experience."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The company has experienced consistent growth for the last five years. __________, its market share has doubled.",
        "Question": "Which word best completes the text?",
        "AnswerChoiceA": "As a result",
        "AnswerChoiceB": "Nevertheless",
        "AnswerChoiceC": "For example",
        "AnswerChoiceD": "On the contrary",
        "CorrectAnswer": "As a result",
        "Explanation": "As a result",
        "Hint": "Look for the outcome of growth."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The author describes the protagonist's struggle in vivid detail. __________, the supporting characters are underdeveloped.",
        "Question": "Which word best fits the text?",
        "AnswerChoiceA": "In addition",
        "AnswerChoiceB": "On the contrary",
        "AnswerChoiceC": "Conversely",
        "AnswerChoiceD": "However",
        "CorrectAnswer": "However",
        "Explanation": "However",
        "Hint": "Look for opposing ideas."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The new policy will benefit employees. __________, it may increase operational costs for the company.",
        "Question": "Which choice best completes the sentence?",
        "AnswerChoiceA": "Therefore",
        "AnswerChoiceB": "Additionally",
        "AnswerChoiceC": "On the other hand",
        "AnswerChoiceD": "Similarly",
        "CorrectAnswer": "On the other hand",
        "Explanation": "On the other hand",
        "Hint": "Focus on contrasting benefits and costs."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "She prepared thoroughly for the interview. __________, she felt confident walking in.",
        "Question": "Which choice best completes the text?",
        "AnswerChoiceA": "Despite this",
        "AnswerChoiceB": "Therefore",
        "AnswerChoiceC": "In contrast",
        "AnswerChoiceD": "Meanwhile",
        "CorrectAnswer": "Therefore",
        "Explanation": "Therefore",
        "Hint": "Look for an effect based on preparation."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The museum’s collection includes artifacts from ancient Egypt. __________, it houses a large number of medieval European paintings.",
        "Question": "Which transition best completes the text?",
        "AnswerChoiceA": "On the contrary",
        "AnswerChoiceB": "Furthermore",
        "AnswerChoiceC": "Nevertheless",
        "AnswerChoiceD": "In contrast",
        "CorrectAnswer": "Furthermore",
        "Explanation": "Furthermore",
        "Hint": "Look for an addition or continuation."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The weather forecast predicted rain all day. __________, it remained sunny throughout the afternoon.",
        "Question": "Which transition completes the text most logically?",
        "AnswerChoiceA": "However",
        "AnswerChoiceB": "Similarly",
        "AnswerChoiceC": "Consequently",
        "AnswerChoiceD": "For instance",
        "CorrectAnswer": "However",
        "Explanation": "However",
        "Hint": "Pay attention to how the actual weather contradicts the forecast."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The results were promising, indicating that the treatment could be effective. __________, further tests are needed to confirm its safety.",
        "Question": "Which transition completes the text logically?",
        "AnswerChoiceA": "Thus",
        "AnswerChoiceB": "For example",
        "AnswerChoiceC": "Nevertheless",
        "AnswerChoiceD": "As a result",
        "CorrectAnswer": "Nevertheless",
        "Explanation": "Nevertheless",
        "Hint": "Look for a need for further confirmation despite positive outcomes."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "She spent hours studying for the exam. __________, she passed with flying colors.",
        "Question": "Which word best completes the sentence?",
        "AnswerChoiceA": "In contrast",
        "AnswerChoiceB": "Consequently",
        "AnswerChoiceC": "Although",
        "AnswerChoiceD": "However",
        "CorrectAnswer": "Consequently",
        "Explanation": "Consequently",
        "Hint": "Think about the result of the preparation."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The book was critically acclaimed. __________, it failed to gain popularity with readers.",
        "Question": "Which transition fits best here?",
        "AnswerChoiceA": "On the other hand",
        "AnswerChoiceB": "Additionally",
        "AnswerChoiceC": "For instance",
        "AnswerChoiceD": "Similarly",
        "CorrectAnswer": "On the other hand",
        "Explanation": "On the other hand",
        "Hint": "Pay attention to how the critical response differs from reader reception."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The product launch was successful. __________, sales exceeded expectations in the first quarter.",
        "Question": "Which word completes the sentence logically?",
        "AnswerChoiceA": "Similarly",
        "AnswerChoiceB": "In contrast",
        "AnswerChoiceC": "As a result",
        "AnswerChoiceD": "Meanwhile",
        "CorrectAnswer": "As a result",
        "Explanation": "As a result",
        "Hint": "Focus on how one event leads to another."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "He enjoyed hiking in the mountains. __________, he was afraid of heights and avoided the edges of cliffs.",
        "Question": "Which choice best fits the text?",
        "AnswerChoiceA": "For example",
        "AnswerChoiceB": "However",
        "AnswerChoiceC": "Therefore",
        "AnswerChoiceD": "Consequently",
        "CorrectAnswer": "However",
        "Explanation": "However",
        "Hint": "Look for a contrast between preferences and fears."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The city implemented stricter traffic regulations. __________, congestion decreased significantly.",
        "Question": "Which word best fits the sentence?",
        "AnswerChoiceA": "In contrast",
        "AnswerChoiceB": "Therefore",
        "AnswerChoiceC": "Nevertheless",
        "AnswerChoiceD": "On the other hand",
        "CorrectAnswer": "Therefore",
        "Explanation": "Therefore",
        "Hint": "Look for the outcome of the city’s action."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The team worked overtime to complete the project. __________, they submitted it ahead of the deadline.",
        "Question": "Which word completes the text logically?",
        "AnswerChoiceA": "In addition",
        "AnswerChoiceB": "Consequently",
        "AnswerChoiceC": "However",
        "AnswerChoiceD": "Nevertheless",
        "CorrectAnswer": "Consequently",
        "Explanation": "Consequently",
        "Hint": "Focus on the result of working overtime."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "She was extremely talented in music. __________, her academic performance was mediocre.",
        "Question": "Which choice completes the text most logically?",
        "AnswerChoiceA": "Similarly",
        "AnswerChoiceB": "In contrast",
        "AnswerChoiceC": "Consequently",
        "AnswerChoiceD": "Meanwhile",
        "CorrectAnswer": "In contrast",
        "Explanation": "In contrast",
        "Hint": "Look for a comparison between two opposite traits."
    },
    {
        "TypeofQuestion": "Transition",
        "Passage": "The company has a strong environmental policy. __________, it has invested heavily in renewable energy.",
        "Question": "Which word best completes the sentence?",
        "AnswerChoiceA": "Nevertheless",
        "AnswerChoiceB": "For example",
        "AnswerChoiceC": "In contrast",
        "AnswerChoiceD": "On the contrary",
        "CorrectAnswer": "For example",
        "Explanation": "For example",
        "Hint": "Focus on how renewable energy supports the environmental policy."
    }
]